sudo: required

services:
  - docker

branches:
  only:
    - /^([0-9.]+)(-\w+)?$/

script:
  - docker build --build-arg SERVERLESS_VERSION=$TRAVIS_TAG -t serverless_test:$TRAVIS_TAG .
  - echo 'Test'
  - docker run serverless_test:$TRAVIS_TAG --version | grep $TRAVIS_TAG